<?php

namespace AppBundle\Repository;

/**
 * WineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineRepository extends \Doctrine\ORM\EntityRepository
{
}
